name: colon
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.9.0=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.5=py_0
  - blinker=1.4=py37_0
  - brotlipy=0.7.0=py37h7b6447c_1000
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.6.20=hecda079_0
  - cachetools=4.1.0=py_1
  - certifi=2020.6.20=py37hc8dfbb8_0
  - cffi=1.14.0=py37he30daa8_1
  - chardet=3.0.4=py37_1003
  - click=7.1.2=py_0
  - cloudpickle=1.5.0=py_0
  - cryptography=2.9.2=py37h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.1=py37h516909a_0
  - dask-core=2.21.0=py_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - enum34=1.1.10=py37hc8dfbb8_1
  - freetype=2.10.2=h5ab3b9f_0
  - google-auth=1.17.2=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.27.2=py37hf8bcb03_0
  - h5py=2.10.0=py37hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - idna=2.10=py_0
  - imagecodecs-lite=2019.12.3=py37h03ebfcd_1
  - imageio=2.9.0=py_0
  - importlib-metadata=1.7.0=py37_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2020.1=217
  - ipykernel=5.3.3=py37h5ca1d4c_0
  - ipython=7.16.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.17.1=py37_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.5=py_0
  - jsonschema=3.2.0=py37_1
  - jupyter_client=6.1.6=py_0
  - jupyter_core=4.6.3=py37_0
  - jupyterlab=2.2.0=py_0
  - jupyterlab_server=1.2.0=py_0
  - kiwisolver=1.2.0=py37hfd86e86_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.12.3=hd408876_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - lz4-c=1.9.2=he6710b0_0
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.1=py37h14c3975_1
  - matplotlib=3.3.0=1
  - matplotlib-base=3.3.0=py37hd478181_1
  - mistune=0.8.4=py37h14c3975_1001
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.1.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - nbconvert=5.6.1=py37_1
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he6710b0_1
  - networkx=2.4=py_1
  - nibabel=3.1.1=py_0
  - ninja=1.9.0=py37hfd86e86_0
  - notebook=6.0.3=py37_0
  - numpy=1.18.5=py37ha1c710e_0
  - numpy-base=1.18.5=py37hde5b4d6_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py37_0
  - openssl=1.1.1g=h516909a_0
  - packaging=20.4=py_0
  - pandoc=2.10=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.7.0=py_0
  - pathlib=1.0.1=py37hc8dfbb8_2
  - pexpect=4.8.0=py37_1
  - pickleshare=0.7.5=py37_1001
  - pillow=7.2.0=py37hb39fc2d_0
  - pip=20.1.1=py37_1
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.5=py_0
  - protobuf=3.12.3=py37he6710b0_0
  - ptyprocess=0.6.0=py37_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_2
  - pydicom=2.0.0=pyh9f0ad1d_0
  - pygments=2.6.1=py_0
  - pyjwt=1.7.1=py37_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyrsistent=0.16.0=py37h7b6447c_0
  - pysocks=1.7.1=py37_1
  - python=3.7.7=hcff3b4d_5
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.5.1=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pywavelets=1.1.1=py37h03ebfcd_1
  - pyyaml=5.3.1=py37h8f50634_0
  - pyzmq=19.0.1=py37he6710b0_1
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.0=py_0
  - scikit-image=0.17.2=py37h0da4684_1
  - scipy=1.5.0=py37h0b6359f_0
  - send2trash=1.5.0=py37_0
  - setuptools=49.2.0=py37_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h62c20be_0
  - tensorboard=2.3.0=py_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.10.0=py_0
  - torchvision=0.6.1=py37_cu101
  - tornado=6.0.4=py37h7b6447c_1
  - traitlets=4.3.3=py37_0
  - urllib3=1.25.9=py_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - werkzeug=1.0.1=py_0
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - zeromq=4.3.2=he6710b0_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h0b5b093_0
  - pip:
    - tifffile==2020.7.24
    - torchsummary==1.5.1
prefix: /home/chan/miniconda3/envs/colon

